Create test_bot.py
Skip to content
niku-bot-QUHq
Repository navigation
Code
Issues
Actions
Python application
Create python-app.yml #1
build
failed now in 15s
1s
1s
0s
7s
1s
##[debug]Evaluating condition for step: 'Lint with flake8'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Lint with flake8
##[debug]Loading inputs
##[debug]Loading env
Run # stop the build if there are Python syntax errors or undefined names
##[debug]/usr/bin/bash -e /home/runner/work/_temp/4b890b96-0832-4171-9f00-7785d6125f42.sh
0
./bot.py:16:1: W293 blank line contains whitespace
./bot.py:31:1: E302 expected 2 blank lines, found 1
./bot.py:39:1: E302 expected 2 blank lines, found 1
./bot.py:42:1: W293 blank line contains whitespace
./bot.py:45:1: W293 blank line contains whitespace
./bot.py:47:1: W293 blank line contains whitespace
./bot.py:51:1: W293 blank line contains whitespace
./bot.py:53:1: W293 blank line contains whitespace
./bot.py:55:128: E501 line too long (134 > 127 characters)
./bot.py:63:1: W293 blank line contains whitespace
./bot.py:66:1: W293 blank line contains whitespace
./bot.py:68:1: W293 blank line contains whitespace
./bot.py:73:1: E302 expected 2 blank lines, found 1
3     E302 expected 2 blank lines, found 1
1     E501 line too long (134 > 127 characters)
9     W293 blank line contains whitespace
13
##[debug]Finishing: Lint with flake8
0s
============================= test session starts ==============================
platform linux -- Python 3.10.20, pytest-9.1.1, pluggy-1.6.0
rootdir: /home/runner/work/niku-bot-QUHq/niku-bot-QUHq
plugins: anyio-4.14.0
collected 0 items
============================ no tests ran in 0.00s =============================
Error: Process completed with exit code 5.
##[debug]Finishing: Test with pytest
0s
##[debug]Evaluating condition for step: 'Post Set up Python 3.10'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> false
##[debug]Result: false
1s
##[debug]Evaluating condition for step: 'Post Run actions/checkout@v4'
##[debug]Evaluating: always()
##[debug]Evaluating always:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Post Run actions/checkout@v4
##[debug]Loading inputs
##[debug]Evaluating: github.repository
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'repository'
##[debug]=> 'ivanm696/niku-bot-QUHq'
##[debug]Result: 'ivanm696/niku-bot-QUHq'
##[debug]Evaluating: github.token
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'token'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Node 20 is being deprecated. This workflow is running with Node 24 by default. If you need to temporarily use Node 20, you can set the ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true environment variable. For more information see: https://github.blog/changelog/2025-09-19-deprecation-of-node-20-on-github-actions-runners/
Post job cleanup.
##[debug]Getting git version
/usr/bin/git version
git version 2.54.0
##[debug]0
##[debug]git version 2.54.0
##[debug]
##[debug]Set git useragent to: git/2.54.0 (github-actions-checkout)
::add-mask::***
Temporarily overriding HOME='/home/runner/work/_temp/4e06644d-ff88-4491-a8e5-a582a3261ebe' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/niku-bot-QUHq/niku-bot-QUHq
##[debug]0
##[debug]
/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
##[debug]1
##[debug]
/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
##[debug]0
##[debug]
/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
http.https://github.com/.extraheader
##[debug]0
##[debug]http.https://github.com/.extraheader
##[debug]
/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
##[debug]0
##[debug]
/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
##[debug]0
##[debug]
/usr/bin/git config --local --name-only --get-regexp ^includeIf\.gitdir:
##[debug]1
##[debug]
/usr/bin/git submodule foreach --recursive git config --local --show-origin --name-only --get-regexp remote.origin.url
##[debug]0
##[debug]
##[debug]Unsetting HOME override
##[debug]Node Action run completed with exit code 0
##[debug]Finishing: Post Run actions/checkout@v4
0s